id: P000745
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1017462
  title: མན་ངག་བཀའ་རྒྱ་མ
  author: ''
  volumes:
    a7efce0ee6ff46e3926236120aefc6b5:
      image_group_id: I1PD440
      title: ''
      volume_number: 1
      total_pages: 606
      base_file: v001.txt
