id: P000745
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 2021-12-16 16:40:36.670991
source_metadata:
  id: bdr:W00EGS1017462
  title: མན་ངག་བཀའ་རྒྱ་མ
  author: ''
  volumes:
    a7efce0ee6ff46e3926236120aefc6b5:
      image_group_id: I1PD440
      title: ''
      volume_number: 1
      total_pages: 606
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
